### ISSUE TITLE
Investigate how to get videos/screenshots of failed tests in GHA using VScode extension tester

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-vscode#441]
Investigate how to get videos/screenshots of failed tests in GHA using VScode extension tester.
https://github.com/redhat-developer/vscode-extension-tester

**Comment by gilbysunil14** [comment]
Follow these steps to take screenshots in GHA and archive it

1. The following code `VSBrowser.instance.takeScreenshot("fileName")` will take screenshot of the existing browser window.
2. The screenshot will be saved in a temporary location. We have to copy the same to a known location in the project folder `screenshots`. For this use `afterAll()` hook to copy the screenshot from the temporary location to a new location.
3. We can get the temporary location of the screen shot from `VSBrowser.instance.getScreenshotsDir()`.
4. For archiving screenshots in GHA, an additional step needs to be added which is `Archive screenshots`. An example is shown below:
```
- name: Archive screenshots
        if: always() && runner.os == 'linux' && matrix.targetVSCode == 'latest'
        uses: actions/upload-artifact@v3
        with:
          name: liberty-run-tests-screenshots-${{ github.sha }}
          path: ./screenshots/*.png
          if-no-files-found: warn
          retention-days: 7
```
